#!/bin/bash

export __self+=" .sta.xtfx.net"
export PATH="${HOME}/bin:$PATH"

[[ $- == *i* ]] &&
    [[ -f ~/.app/data/profile/etc/bash/interactive ]] &&
    . ~/.app/data/profile/etc/bash/interactive
