#!/bin/bash

alias diff='git diff --no-index'
alias l='ls -Flh'
alias ll='ls -Flha'
alias t='tree -h -I "*.venv|*.pyc|__pycache__|*.egg-info|node_modules|vendor|.git|go"'
alias tt='t -a'
alias tx='tmux new-session -ADs ${PWD##*/}'

# Git aliases.
alias g='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdcs='git diff --cached --stat'
alias gds='git diff --stat'
alias gl='git log'
alias glg='git log --graph'
alias glgo='git log --graph --oneline'
alias glp='git log --patch'
alias gls='git log --stat'
alias gs='git show'
alias gss='git show --stat'

incognito () { cognito off; }
cognito () {
  case ${1:-on} in
    (on)  [[ -z $HISTFILE ]] && HISTFILE="$HISTFILE__" && unset HISTFILE__;;
    (off) [[ -z $HISTFILE__ ]] && HISTFILE__="$HISTFILE" && unset HISTFILE;;
  esac
}
