#!/bin/bash

alias l='ls -Flh'
alias ll='ls -Flha'
alias t='tree -h -I "*.venv|*.pyc|__pycache__|*.egg-info|node_modules|vendor|.git|go"'
alias tt='t -a'

# Tmux wrappers.
alias th='td .'
alias ty='td ~'
alias tg='td "$(git rev-parse --show-cdup 2>/dev/null)"'
td () ( cd "${1:-.}" && exec tmux new-session -ADs "$PWD" \; "${@:2}" )

# Git aliases.
diffopts='--diff-algorithm=histogram'
alias diff="git diff --no-index $diffopts"
# Higher-speed keystrokes.
alias q="git status"
alias qa="git add --patch"
alias qaa="git add --all"
alias qs="git show $diffopts"
alias qsq="git show --stat"
alias qw="git diff $diffopts"
alias qwq="git diff --stat"
alias qww="git diff --cached $diffopts"
alias qwwq="git diff --cached --stat"
# Lower-speed keystrokes.
alias qc="git commit"
alias qca="git commit --amend"
alias qcam="git commit --amend --message"
alias qcan="git commit --amend --no-edit"
alias qcc="git commit --all"
alias qcca="git commit --all --amend"
alias qccam="git commit --all --amend --message"
alias qccan="git commit --all --amend --no-edit"
alias qccm="git commit --all --message"
alias qcm="git commit --message"
alias ql="git log $diffopts"
alias qlg="git log --graph $diffopts"
alias qlgo="git log --graph --oneline $diffopts"
alias qlp="git log --patch $diffopts"
alias qls="git log --stat"
alias qp!="git push --force"
alias qp="git push"

incognito () { cognito off; }
cognito () {
  case ${1:-on} in
    (on)  [[ -z $HISTFILE ]] && HISTFILE="$HISTFILE__" && unset HISTFILE__;;
    (off) [[ -z $HISTFILE__ ]] && HISTFILE__="$HISTFILE" && unset HISTFILE;;
  esac
}
