#!/bin/bash

alias diff='command diff --color -u'
alias l='ls -Flh'
alias ll='ls -Flha'
alias t='tree -h -I "*.venv|*.pyc|__pycache__|*.egg-info|node_modules|vendor|.git|go"'
alias tt='t -a'

# Git aliases.
alias g='git'
alias gs='g s'
alias gd='g d'
alias gdc='g dc'
alias gdd='g dc'

incognito () { cognito off; }
cognito () {
  case ${1:-on} in
    (on)  [[ -z $HISTFILE ]] && HISTFILE="$HISTFILE__" && unset HISTFILE__;;
    (off) [[ -z $HISTFILE__ ]] && HISTFILE__="$HISTFILE" && unset HISTFILE;;
  esac
}
