#!/bin/sh

export AIMAN="${AIMAN:-${AIMOD:+"$AIMOD "}$AIGEN}"
export AITID="${AITID:-"$(uuidgen | tr ABCDEF abcdef)"}"
export AISID="${AISID:-"$AITID"}"
export AIGEN="${AIGEN:-"claude"}"
export AIMOD="${AIMOD:-}"
export AIWTF="${AIWTF:-}"

ai:sys () (
  set -${AIWTF:+x}euo pipefail
  cat <<EOF | tr '[:lower:]' '[:upper:]'
YOU ARE ${AIMOD:-"(UNDIFFERENTIATED)"} $AIGEN SPEAKING TO ${AIMAN:-"A HUMAN"}.
EOF
)

ai:sid () (
  set -${AIWTF:+x}euo pipefail
  if test "$AIMAN" = "${AIMOD:+"$AIMOD "}$AIGEN"; then
    ai:sys >&2
    return 1
  fi
  if ! test -s ~/".$AIGEN"/*/*/"$AITID.jsonl.$AIGEN${AIMOD:+"~$AIMOD"}.jsonl"; then
    if test -s ~/".$AIGEN"/*/*/"$AITID.jsonl"; then
      find ~/".$AIGEN"/*/*/"$AITID.jsonl"* -empty -delete
      find ~/".$AIGEN"/*/*/"$AITID.jsonl" -exec cp -an "{}" "{}.$AIGEN.jsonl" \;
      find ~/".$AIGEN"/*/*/"$AITID.jsonl" -exec cp -an "{}" "{}.$AIGEN${AIMOD:+"~$AIMOD"}.jsonl" \;
    elif test -e ~/".$AIGEN"/*/*/"$AITID.jsonl"; then
      find ~/".$AIGEN"/*/*/"$AITID.jsonl"* -delete
    fi
  fi
  if test -s ~/".$AIGEN"/*/*/"$AITID.jsonl.$AIGEN~$AIMOD.jsonl"; then
    tail -n1 ~/".$AIGEN"/*/*/"$AITID.jsonl.$AIGEN~$AIMOD.jsonl" | jq -er '.session_id//.sessionId//empty'
  elif test -s ~/".$AIGEN"/*/*/"$AITID.jsonl.$AIGEN.jsonl"; then
    tail -n1 ~/".$AIGEN"/*/*/"$AITID.jsonl.$AIGEN.jsonl" | jq -er '.session_id//.sessionId//empty'
  elif test -s ~/".$AIGEN"/*/*/"$AISID.jsonl"; then
    echo >&2 "WARNING: No '$AITID.jsonl.*' sessions found; using old session '$AISID.jsonl'."
    echo "$AISID"
  elif test -s ~/".$AIGEN"/*/*/"$AITID.jsonl"; then
    echo >&2 "WARNING: No '$AISID.jsonl' session found; forking base session '$AITID.jsonl'."
    echo "$AITID"
  elif test "$AITID" != "$AISID"; then
    echo >&2 "WARNING: No '$AITID.jsonl' session found; starting new session '$AISID.jsonl'."
    echo "$AISID"
  else
    echo "$AITID"
  fi
)

ai:gen () (
  set -${AIWTF:+x}euo pipefail
  case "$AIGEN~$AIMOD" in
    ("claude~")           set -- --model opusplan --fallback-model sonnet   "$@" ;;
    ("claude~customer")   set -- --model sonnet   --fallback-model haiku    "$@" ;;
    ("claude~engineer")   set -- --model opusplan --fallback-model sonnet   "$@" ;;
    ("claude~architect")  set -- --model opus     --fallback-model opusplan "$@" ;;
    ("claude~"*)          set -- --model "$AIMOD" "$@" ;;
  esac
  AISID=$(ai:sid)
  test -s ~/".$AIGEN"/*/*/"$AISID.jsonl" \
    && set -- --resume "$AISID" "$@" \
    || set -- --session-id "$AISID" "$@"
  AIMAN="${AIMOD:+"$AIMOD "}$AIGEN" command "$AIGEN" --append-system-prompt "$(ai:sys)" "$@"
)

ai:cat () (
  set -${AIWTF:+x}euo pipefail
  TIMEFORMAT=$'\n'" $AIGEN${AIMOD:+ ($AIMOD)} / %P CPU / %3lRs / $AITID"
  TIMEFMT=$'\n'" $AIGEN${AIMOD:+ ($AIMOD)} / %P CPU / %*Es / $AITID"
  AISID=$(ai:sid)
  time (
    sed -ur '$s, < /dev/null$,,' \
    | ai:gen "$@" --dangerously-skip-permissions --print --verbose --output-format=stream-json \
    | if test -s ~/".$AIGEN"/*/*/"$AITID.jsonl"; then
        tee -a ~/".$AIGEN"/*/*/"$AITID.jsonl.$AIGEN${AIMOD:+"~$AIMOD"}.jsonl"
      else
        cat -u
      fi \
    | jq --unbuffered --join-output '"\(.message.content[]?.text//empty)\n"//"\u0007"' \
    | sed -ur $'1s,^\u0007*,,;$s,\u0007*$,,;s,\u0007+,\\n(TODO: TOOLS RAN HERE)\\n\\n,g'
  )
)

claude () { AIGEN=claude ai:gen "$@"; }

alias "WTF= AIWTF=x "

alias "Customer= AIMOD=customer "
alias "Engineer= AIMOD=engineer "
alias "Architect= AIMOD=architect "
alias "Haiku= AIMOD=haiku "
alias "Sonnet= AIMOD=sonnet "
alias "Opus= AIMOD=opus "

if test -n "$AIMAN"; then
  alias "Claude,= AIGEN=claude ai:cat << '$AITID'"
  alias "Assistant,= ai:cat << '$AITID'"
  alias "Agent,= ai:cat << '$AITID'"
  alias "AI,= ai:cat << '$AITID'"
else
  alias "Claude,= AIGEN=claude ai:cat << ''"
  alias "Assistant,= ai:cat << ''"
  alias "Agent,= ai:cat << ''"
  alias "AI,= ai:cat << ''"
fi
