#!/bin/sh

# ATTN: LLM
export __ATTN_NAME="${__ATTN_NAME:-claude}"
export __ATTN_UUID="${__ATTN_UUID:-$(uuidgen | tr ABCDEF abcdef)}"
attn () (
  set -euo pipefail
  if test -s ~/".$__ATTN_NAME"/*/*/"$__ATTN_UUID.jsonl.$__ATTN_NAME.jsonl"; then
    __ATTN_UUID=$(tail -n1 ~/".$__ATTN_NAME"/*/*/"$__ATTN_UUID.jsonl.$__ATTN_NAME.jsonl" | jq -er '.session_id//.sessionId//empty')
  elif test -e ~/".$__ATTN_NAME"/*/*/"$__ATTN_UUID.jsonl.$__ATTN_NAME.jsonl"; then
    rm -f ~/".$__ATTN_NAME"/*/*/"$__ATTN_UUID.jsonl.$__ATTN_NAME.jsonl"
  fi
  test -s ~/".$__ATTN_NAME"/*/*/"$__ATTN_UUID.jsonl" \
    && set -- "$@" --resume "$__ATTN_UUID" \
    || set -- "$@" --session-id "$__ATTN_UUID"
  TIMEFMT=" $__ATTN_NAME / %P CPU / %*Es / $__ATTN_UUID"
  time command "$__ATTN_NAME" "$@"
)
attnc () (
  set -euo pipefail
  set -- "$@" --dangerously-skip-permissions --print --verbose --output-format=stream-json
  if test -s ~/".$__ATTN_NAME"/*/*/"$__ATTN_UUID.jsonl"; then
    find ~/".$__ATTN_NAME"/*/*/"$__ATTN_UUID.jsonl" -exec cp -an {} {}.$__ATTN_NAME.jsonl \;
    exec 3>> ~/".$__ATTN_NAME"/*/*/"$__ATTN_UUID.jsonl.$__ATTN_NAME.jsonl"
  else
    exec 3>> /dev/null
  fi
  attn "$@" \
  | tee -a /dev/fd/3 \
  | jq --unbuffered --join-output '"\(.message.content[]?.text//empty)\n"//"\u0007"' \
  | sed -r $'1s,^\u0007+,,;$s,\u0007+$,,;s,\u0007+,\\n\\n,g'
)
alias "ATTN:= attnc << '-- ' "

claude () { __ATTN_NAME=claude attn "$@"; }
alias "Claude,= __ATTN_NAME=claude attnc << '-- '"

# Liked or used often.
if ls --color=auto >/dev/null 2>&1; then
  alias ls='ls -F --color=auto'
else
  alias ls='ls -F -G'
fi
alias l='ls -Flh'
alias ll='ls -Flha'
alias t='tree --charset=ascii -h -I "*.venv|*.pyc|__pycache__|*.egg-info|node_modules|vendor|.git|go|.pytest_cache|htmlcov"'
tree () { set -- ${COLORTERM:+-C} "$@"; command tree "$@"; }
alias tt='t -a'
alias v='. *.venv/bin/activate'

# JIRA wrapper.
jira () (
  for x in ~/.tokens/JIRA_*; do export ${x##*/}=$(<$x); done
  command jira "$@"
)

# Grep wrappers.
alias ge='grep --extended-regexp'
alias gi='ge --ignore-case'
alias gr='ge --recursive'
alias gri='gi --recursive'
alias grep='grep --colour=auto --devices=skip --binary-files=without-match --exclude-dir={".*[.]venv",__pycache__,"*.egg-info",node_modules,vendor,.git,go,.pytest_cache,htmlcov} --exclude={".*[.]pyc",".coverage","*[.]min[.]*","*/dist/*[.]js","*/dist/*[.]js[.]*",}'

# Tmux wrappers.
alias th='td .'
alias ty='td ~'
alias tg='td "$(git rev-parse --show-cdup 2>/dev/null)"'
td () (
  set -e; cd "${1:-.}"; shift
  exec tmux new -ADs "$PWD;" set @session_name "${PWD##*/};" "$@"
)

# Venv + Tmux wrappers.
alias vh='VIRTUAL_ENV="glob:*.venv" th'
alias vg='VIRTUAL_ENV="glob:*.venv" tg'
alias vd='VIRTUAL_ENV="glob:*.venv" td'

normaldiffs () { _GIT_DIFF_ARGS=' -c core.pager= -c diff.noprefix='; }
prettydiffs () { _GIT_DIFF_ARGS=; }

# Lazy load nvm.
nvm () {
  unset nvm
  export NVM_DIR=${NVM_DIR:-~/.nvm}
  . "$NVM_DIR/nvm.sh"
  . "$NVM_DIR/${SHELL##*/}_completion"
  [[ $(type -t nvm) == function ]] &&
    nvm "$@"
}

# Push and compile terminfo files.
terminfo-ssh () {
  for host in "$@"; do
    ssh -A "$host" <"${ELLIPSIS}"data/profile/iterm2/iterm2-direct-compat.terminfo -- \
      bash -c 'cat > /tmp/terminfo && tic -x /tmp/terminfo && rm -f /tmp/terminfo'
  done
}

# Output current ECR repo.
ecr () {
  curl -s 169.254.169.254/latest/dynamic/instance-identity/document |
    jq -r '"\(.accountId).dkr.ecr.\(.region).amazonaws.com"'
}

# Output current region.
region () {
  curl -s 169.254.169.254/latest/dynamic/instance-identity/document |
    jq -r '.region'
}

# TERM eic-ssh ...
eic-ssh () {
  TERM=xterm-256color command eic-ssh $@
}
