#!/bin/zsh

# Bash compat.
alias help=run-help

# Git aliases.
alias diff="git diff --no-index"

# Git operations framed as mutable QUERIES against three stacked TREES:
#   - Input operations (eg. add/commit) start at filesystem and push data IN.
#       TREE#1 [fs] -> TREE#2 [index] -> TREE#3 [repo]
#   - Output operations (eg. checkout/reset) start at repository and pull data OUT.
#       TREE#1 [repo] -> TREE#2 [index] -> TREE#3 [fs]
#   - Other operations (eg. status/diff) use INPUT order unless OUTPUT is obvious.
# Query (verbose)
alias q="git status"
# Query2 (quiet)
alias qq="git status --short"
# Query Add (interactive; any tracked file)
alias qa="git add --patch"
# Query2 Add (interactive; any worktree file)
alias qaq="git add --patch \$(git rev-parse --show-toplevel)"
# Query Add2 (batch; any tracked file)
alias qaa="git add --all"
# Query2 Add2 (batch; any worktree file)
alias qaaq="git add --all \$(git rev-parse --show-toplevel)"
# Query Delete (interactive; updates index)
alias qd="git reset --patch"
# Query Delete (batch; resets index)
alias qd!="git reset --mixed"
# Query Delete2 (interactive; updates worktree)
alias qdd="git checkout --patch"
# Query Delete2 (batch; resets worktree)
alias qdd!="git reset --hard"
# Query2 Delete2 (interactive; cleanup untracked files)
alias qddq="git clean -i"
# Query2 Delete2 (force; cleanup untracked files)
alias qddq!="git clean -fd"
# Query State Quietly (last update)
alias qsq="git\${=_GIT_DIFF_ARGS} show --stat"
# Query State (last update; verbose)
alias qs="git\${=_GIT_DIFF_ARGS} show --patch"
# Query State2 (recent updates)
alias qssq="git log --stat"
# Query2 State2 (recent updates; verbose)
alias qss="git log --patch"
# Query Upstream (show remotes)
alias qu="git remote --verbose"
# Query2 Upstream (show remotes; query server)
alias quq="git ls-remote --symref"
# Query Upstream2 (sync remotes)
alias quu="git remote --verbose update --prune"
# Query TREE#1 Quietly (worktree)
alias qwq="git\${=_GIT_DIFF_ARGS} diff --stat"
# Query TREE#1 (worktree; patch)
alias qw="git\${=_GIT_DIFF_ARGS} diff"
# Query TREE#2 Quietly (index)
alias qwwq="git\${=_GIT_DIFF_ARGS} diff --cached --stat"
# Query TREE#2 (index; show patch)
alias qww="git\${=_GIT_DIFF_ARGS} diff --cached"
# Query Commits ...
alias qc="git commit"
alias qca="git commit --amend"
alias qcam="git commit --amend --message"
alias qcan="git commit --amend --no-edit"
alias qcc="git commit --all"
alias qcca="git commit --all --amend"
alias qccam="git commit --all --amend --message"
alias qccan="git commit --all --amend --no-edit"
alias qccm="git commit --all --message"
alias qcm="git commit --message"
alias qp!="git push --force"
alias qp="git push"


incognito () { cognito off; }
cognito () {
  case ${1:-on} in
    (on)  [[ -z $HISTFILE ]] && fc -WIP && HISTFILE="$HISTFILE__" && unset HISTFILE__;;
    (off) [[ -z $HISTFILE__ ]] && HISTFILE__="$HISTFILE" && fc -WIp && unset HISTFILE;;
  esac
}
