#!/bin/bash

# I'm human, thanks
if [[ $(date +%Z) == 'UTC' ]]; then
    export TZ='America/Chicago'
fi

export TERM="${TERM:-dumb}"
export EDITOR='vim'

export VIRTUAL_ENV_DISABLE_PROMPT=true

[[ ${TERM} == dumb ]] &&
    return 0

# Better shell scripting experience:
#   - Word split on newline ONLY.
#   - Disable pathname expansion for unquoted words.
#   - Patterns may expand to zero words.
#   - Patterns may use extended matching @(...) operators.
# With respect to completion routines, `extglob` is already enabled. Sadly, all
# the others interfere with widespread shell conventions and scripts.
#IFS=$'\n'
#set -f
#setopt -o nullglob
#setopt -o extglob

# ZR exports.
export STARTERVIEW=$(
  setopt -o nullglob
  printf '%s\n' ~/zr/ziprecruite[r] ~/ziprecruite[r] /var/starterview |
    head -n1
)
export ZR_WIKI=$(
  setopt -o nullglob
  printf '%s\n' ~/zr/wik[i] "$STARTERVIEW"/.zr-wiki |
    head -n1
)
export SALTSTACK=~/zr/saltstack

: ${DEVELOPER_DIR:=$(xcode-select --print-path 2> /dev/null)}
for x in \
  /usr{,/local}/share/zsh-completion/zsh_completion \
  {,/usr/local}/etc/zsh_completion \
  {,$DEVELOPER_DIR}/usr/share/git{,-core}/git-{prompt.sh,completion.zsh} \
  ${ELLIPSIS}data/profile/vim/plugged/fzf/shell/completion.zsh \
;
do
    [[ $x == */git-completion.zsh ]] &&
      continue # TODO
    [[ -r ${x} ]] &&
        . ${x}
done

_ps1 () { (

    local s=( )
    if [[ ${HOSTNAME} =~ ^(ca|anthonyr)- ]]; then
        s+=("%F{green}\u2605")
    else
        s+=("%F{red}\u2691")
    fi
    [[ ${SSH_CONNECTION} =~ [0-9.]+ ]] &&
        s+=("%F{blue}\u21c5")
    ((${#s})) &&
        s=" ${s[*]} "

    print -n -- "\
%f%s  \u239e %D{%l:%M%P} %F{yellow}%m${s}
%f%s  \u23a5  \$(__git_ps1 '%%F{yellow}%s ' 2>/dev/null)%f%s%40<...<%~%<<
%f%s  \u23a5%(!.%F{red}.%f%s)\u25b6 %f%s"

) }

precmd() {
  # Change the window title of X terminals
  case ${TERM} in
    [ixatE]term*|rxvt*|gnome*|interix)
      echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\007"
      ;;
    tmux|screen)
      echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\033\\"
      ;;
  esac
  # Update SSH_AUTH_SOCK within running shells
  if [[ -n ${TMUX} && -n ${SSH_AUTH_SOCK} ]]; then
      unset SSH_AUTH_SOCK
      export $(tmux show-environment | grep ^SSH_AUTH_SOCK)
  fi
}

if ls --color=auto >/dev/null 2>&1; then
  alias ls='ls -F --color=auto'
else
  alias ls='ls -F -G'
fi

if type -p dircolors >/dev/null ; then
  if [[ -f ~/.dir_colors ]] ; then
    eval $(dircolors -b ~/.dir_colors)
  elif [[ -f /etc/DIR_COLORS ]] ; then
    eval $(dircolors -b /etc/DIR_COLORS)
  fi
fi

zmodload zsh/complist

bindkey -e
bindkey "^[[F" end-of-line
bindkey "^[[H" beginning-of-line
bindkey "\x15" backward-kill-line
bindkey -M menuselect '^[[Z' reverse-menu-complete
[[ -r ${ELLIPSIS}data/profile/vim/plugged/fzf/shell/key-bindings.zsh ]] &&
  . ${ELLIPSIS}data/profile/vim/plugged/fzf/shell/key-bindings.zsh

unalias run-help
autoload run-help
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select

setopt promptpercent
setopt promptsubst
setopt extendedglob
setopt histfcntllock
setopt histignorespace
setopt histignorealldups
setopt histreduceblanks
setopt histlexwords
setopt sharehistory
setopt extendedhistory

HISTFILE=${ELLIPSIS}var/cache/zsh/history
SAVEHIST=10000000
HISTSIZE=10000000
HISTORY_IGNORE='([bf]g|[bf]g |exit|exit |cognito|cognito |incognito|incognito )'

KEYTIMEOUT=20
NULLCMD=:

PROMPT=$(_ps1)

WORDCHARS='*?_[]~=&;!#$%^(){}<>'

[[ -r ${ELLIPSIS}data/profile/zsh/aliases ]] &&
    . ${ELLIPSIS}data/profile/zsh/aliases
