#!/bin/bash


declare -x PATH="${HOME}/bin:$PATH" \
           ELLIPSIS=~/.../self/ \
           ELLIPSIS_HOSTS+=" .sta.xtfx.net"


if [[ $- == *i* ]]; then
    declare -x HOME=${HOME%%/}/
    declare -x TMPDIR=${HOME}tmp/
    declare -x _TMPDIR=/run/user/${USER}/tmp/

    ! [[ -d ${_TMPDIR} ]] &&
        mkdir --mode=0700 ${_TMPDIR} &&
        mkdir ${_TMPDIR}/{dl,misc}
    ! [[ $(readlink -f ${TMPDIR})/ == ${_TMPDIR} ]] &&
        rm -f ${TMPDIR%/} &&
        ln -s ${_TMPDIR} ${TMPDIR%/}

    [[ -f ~/.../config && ${UID} == ${EUID} ]] &&
        ( declare -x GIT_DIR=${HOME}...
          ref0=$(git rev-parse HEAD)
          git pull
          ref1=$(git rev-parse HEAD)
          [[ ${ref0} != ${ref1} ]] ) &&
        exec ${BASH}

    [[ -f ${ELLIPSIS}data/profile/etc/bash/interactive ]] &&
    . ${ELLIPSIS}data/profile/etc/bash/interactive
fi
