#!/bin/bash

declare -x PATH="${HOME}/bin:$PATH" \
           ELLIPSIS=~/.../self/ \
           ELLIPSIS_HOSTS+=" .sta.xtfx.net"

declare -x TMPDIR=/tmp/${USER}-tmp-$(head -c 8 < /etc/machine-id)

! [[ -d ${TMPDIR} ]] &&
    mkdir --mode=0700 ${TMPDIR} &&
    mkdir ${TMPDIR}/{dl,misc} &&
    ! [[ -d ~/tmp ]] &&
        ln -s ${TMPDIR} ~/tmp

[[ $- == *i* ]] &&
    [[ -f ${ELLIPSIS}data/profile/etc/bash/interactive ]] &&
    . ${ELLIPSIS}data/profile/etc/bash/interactive
