#!/bin/bash

export _self+=" .sta.xtfx.net"
export PATH="${HOME}/bin:$PATH"

[[ $- == *i* ]] &&
    [[ -f ~/.../self/data/profile/etc/bash/interactive ]] &&
    . ~/.../self/data/profile/etc/bash/interactive
