#!/bin/sh

# Not auto-exported by shells or POSIX.
export PWD HOME PATH SHELL TERM HOSTNAME HOSTTYPE MACHTYPE OSTYPE

# Used in downstream configuration files.
export _ELLIPSIS ELLIPSIS ELLIPSIS_PATH ELLIPSIS_DEBUG

# Let the shell work it out.
HOME=~

# Allow overrides, eg. `_ELLIPSIS=a …`.
: "${_ELLIPSIS:=$HOME/.../}"
: "${ELLIPSIS:=${_ELLIPSIS}self/}"
# Case-insensitive: 0-9 t/rue f/alse y/es n/o
ELLIPSIS_DEBUG="${ELLIPSIS_DEBUG:0:1}"
ELLIPSIS_DEBUG="$((${ELLIPSIS_DEBUG/[TYty]/1}))"

if [ -z "$HOSTNAME" ]; then
  HOSTNAME=$(hostname)
fi

# Detect OSTYPE (darwin, linux, etc).
if [ -z "$OSTYPE" ]; then
  OSTYPE=$(uname -s | tr '[:upper:]' '[:lower:]')
fi

# Detect HOSTTYPE (x86, x86_64, etc).
if [ -z "$HOSTTYPE" ]; then
  HOSTTYPE=$(uname -m | tr '[:upper:]' '[:lower:]')
fi

# Determine if user expects active venv.
if [ -n "$VIRTUAL_ENV" ]; then
  . "$VIRTUAL_ENV/bin/activate"
elif [ "$VSCODE_INJECTION" = 1 ]; then
  if [ -e "$PWD/.venv/bin/activate" ]; then
    . "$PWD/.venv/bin/activate"
  fi
fi || unset VIRTUAL_ENV
