#!/bin/zsh

# Subshell to avoid side effects. Return code determines next step.
(if [[ -x $(type -p git) && -f ${_ELLIPSIS}config && -z ${UID/#$EUID} ]]; then

  # Better working conditions.
  IFS=$'\n'; set -f; setopt -o extendedglob

  # Clean stdout unless interactive.
  if ! [[ $- =~ .*i.* ]]; then
    exec >/dev/null
  fi

  # Clean stderr unless debug.
  if ! ((ELLIPSIS_DEBUG)); then
    exec 2>/dev/null
  fi

  # Logging utils.
  OFF='\e[0m'
  GRAY='\e[30m'
  RED='\e[31m'
  GREEN='\e[32m'
  YELLOW='\e[33m'
  INFO=$GREEN
  WARN=$YELLOW
  ERROR=$RED
  FATAL=$RED
  DEBUG=$GRAY
  info () { at=INFO _log "$@"; }
  warn () { at=WARN _log "$@"; }
  error () { at=ERROR _log "$@"; }
  fatal () { at=FATAL _log "$@"; exit 1; }
  debug () { ((!ELLIPSIS_DEBUG)) || at=DEBUG _log "$@"; }
  say () { at=${at:-DEBUG} _say "$@"; }
  log () { at=${at:-DEBUG} _log "$@"; }
  _say () {
    local format=$1; shift
    printf "## ${!at}$format$OFF\n" "$@"
  }
  _log () {
    local format=$1; shift
    printf "${!at}%-5s $GRAY$(date +%FT%T%z)$OFF $format\n" $at "$@"
  }

  # Shadow `git`.
  export GIT_DIR=$_ELLIPSIS
  export GIT_WORK_TREE=$HOME
  _git_status_calls=0
  git () {
    # Show status exactly once.
    [[ $1 == status ]] && ((_git_status_calls++)) && return
    # Otherwise forward to git binary.
    command git "${@}"
  }

  now=$(date +%s)
  last=$(($(date -r ${_ELLIPSIS}FETCH_HEAD +%s)))
  next=$((last + (60*60*12)))
  read -d '' us them <<<"$(git rev-parse HEAD HEAD@{upstream})"

  # Fetch latest from upstream.
  if ((now > next)); then
    # Inform user of network activity and record new upstream rev.
    say 'Syncing upstream.'
    git fetch --verbose --prune 2>&1
    them=$(git rev-parse HEAD@{upstream})
  fi

  # Bring worktree up-to-date.
  if [[ $us != $them ]] && ! git merge-base --is-ancestor $them $us; then
    # Inform user of the branch-to-merge.
    git status --branch --short
    # Attempt to [safely] bring worktree into compliance.
    if git merge --quiet --ff-only $them; then
      # Either upstream is older than HEAD or the fast-forward worked!
      # Record new HEAD rev now that worktree is also in order.
      us=$(git rev-parse HEAD)
      # If HEAD moved we need to re-exec ASAP.
      if [[ $us == $them ]]; then
        at=INFO say 'Upstream merged (reloading).'
        exit 99
      else
        at=INFO say 'Upstream merged.'
      fi
    else
      # If merge failed, let's retry in an hour.
      TZ=UTC touch -m -t 197001010000.00 ${_ELLIPSIS}FETCH_HEAD
      at=WARN say \
        'Upstream not merged (cd ~; git merge %s).' \
          $(git rev-parse --symbolic-full-name --abbrev-ref HEAD@{upstream})
    fi
  fi

  # Omit --branch here so a clean worktree produces no output.
  git status --short

fi)

case $? in
  (99)
    # Code updated. Re-exec!
    exec -l $ZSH_ARGZERO "${@}"
    ;;
esac

case $- in
  (*i*)
    # Interactive.
    . ${ELLIPSIS}data/profile/zsh/interactive
    ;;
  (*)
    # Non-interactive, unless CODEX_SANDBOX.
    [[ -z $CODEX_SANDBOX ]] || . ${ELLIPSIS}data/profile/zsh/interactive
    ;;
esac
