#!/bin/bash

# Liked or used often.
alias l='ls -Flh'
alias ll='ls -Flha'
alias t='tree --charset=ascii -h -I "*.venv|*.pyc|__pycache__|*.egg-info|node_modules|vendor|.git|go|.pytest_cache|htmlcov"'
alias tt='t -a'
alias v='. *.venv/bin/activate'

# Grep wrappers.
alias ge='grep --extended-regexp'
alias gi='ge --ignore-case'
alias gr='ge --recursive'
alias gri='gi --recursive'
alias grep='grep --colour=auto --devices=skip --binary-files=without-match --exclude-dir={".*[.]venv",__pycache__,"*.egg-info",node_modules,vendor,.git,go,.pytest_cache,htmlcov} --exclude={".*[.]pyc",".coverage","*[.]min[.]*","*/dist/*[.]js","*/dist/*[.]js[.]*",}'

# Tmux wrappers.
alias th='td .'
alias ty='td ~'
alias tg='td "$(git rev-parse --show-cdup 2>/dev/null)"'
td () (
  set -e; cd "${1:-.}"; shift
  exec tmux new -ADs "$PWD;" set @session_name "${PWD##*/};" "$@"
)

# Venv + Tmux wrappers.
alias vh='VIRTUAL_ENV="glob:*.venv" th'
alias vg='VIRTUAL_ENV="glob:*.venv" tg'
alias vd='VIRTUAL_ENV="glob:*.venv" td'

# Git aliases.
alias diff="git diff --no-index"

# Git operations framed as mutable QUERIES against three stacked TREES:
#   - Input operations (eg. add/commit) start at filesystem and push data IN.
#       TREE#1 [fs] -> TREE#2 [index] -> TREE#3 [repo]
#   - Output operations (eg. checkout/reset) start at repository and pull data OUT.
#       TREE#1 [repo] -> TREE#2 [index] -> TREE#3 [fs]
#   - Other operations (eg. status/diff) use INPUT order unless OUTPUT is obvious.
# Query (quiet)
alias q="git status --short"
# Query2 (verbose)
alias qq="git status"
# Query Add (interactive; any tracked file)
alias qa="git add --patch"
# Query Add (interactive; any worktree file)
alias qa!="git add --patch \$(git rev-parse --show-toplevel)"
# Query Add2 (batch; any tracked file)
alias qaa="git add --all"
# Query Add2 (batch; any worktree file)
alias qaa!="git add --all \$(git rev-parse --show-toplevel)"
# Query Delete (interactive; updates index)
alias qd="git reset --patch"
# Query Delete (batch; resets index)
alias qd!="git reset --mixed"
# Query Delete2 (interactive; updates worktree)
alias qdd="git checkout --patch"
# Query Delete2 (batch; resets worktree)
alias qdd!="git reset --hard"
# Query State (last update)
alias qs="git show --stat"
# Query2 State (last update; verbose)
alias qqs="git show --patch"
# Query State2 (recent updates)
alias qss="git log --stat"
# Query2 State2 (recent updates; verbose)
alias qqss="git log --patch"
# Query Upstream (show remotes)
alias qu="git remote --verbose"
# Query2 Upstream (show remotes; query server)
alias qqu="git ls-remote --symref"
# Query Upstream2 (sync remotes)
alias quu="git remote --verbose update --prune"
# Query TREE#1 (worktree)
alias qw="git diff --stat"
# Query TREE#1 (worktree; patch)
alias qqw="git diff"
# Query TREE#2 (index)
alias qww="git diff --cached --stat"
# Query TREE#2 (index; show patch)
alias qqww="git diff --cached"
# Query Commits ...
alias qc="git commit"
alias qca="git commit --amend"
alias qcam="git commit --amend --message"
alias qcan="git commit --amend --no-edit"
alias qcc="git commit --all"
alias qcca="git commit --all --amend"
alias qccam="git commit --all --amend --message"
alias qccan="git commit --all --amend --no-edit"
alias qccm="git commit --all --message"
alias qcm="git commit --message"
alias qp!="git push --force"
alias qp="git push"

incognito () { cognito off; }
cognito () {
  case ${1:-on} in
    (on)  [[ -z $HISTFILE ]] && HISTFILE="$HISTFILE__" && unset HISTFILE__;;
    (off) [[ -z $HISTFILE__ ]] && HISTFILE__="$HISTFILE" && unset HISTFILE;;
  esac
}

# Lazy load nvm.
nvm () {
  unset nvm
  export NVM_DIR=${NVM_DIR:-~/.nvm}
  . "$NVM_DIR/nvm.sh"
  . "$NVM_DIR/bash_completion"
  [[ $(type -t nvm) == function ]] &&
    nvm "$@"
}
