#!/bin/bash

# Liked or used often.
alias l='ls -Flh'
alias ll='ls -Flha'
alias t='tree -h -I "*.venv|*.pyc|__pycache__|*.egg-info|node_modules|vendor|.git|go"'
alias tt='t -a'
alias v='. *.venv/bin/activate'

# Grep wrappers.
alias egrep='grep --extended-regexp'
alias igrep='egrep --ignore-case'
alias rgrep='egrep --recursive'
alias rigrep='igrep --recursive'
alias grep='grep --colour=auto --devices=skip --binary-files=without-match --exclude-dir={".*[.]venv",__pycache__,"*.egg-info",node_modules,vendor,.git,go} --exclude=".*[.]pyc"'

# Tmux wrappers.
alias th='td .'
alias ty='td ~'
alias tg='td "$(git rev-parse --show-cdup 2>/dev/null)"'
td () (
  set -e
  shopt -s nullglob extglob
  cd "${1:-.}"
  if [[ ${VIRTUAL_ENV:0:6} == glob:? ]]; then
    case "${VIRTUAL_ENV:5:1}" in
      (/) VIRTUAL_ENV=$(echo ${VIRTUAL_ENV:5}/);;
      (?) VIRTUAL_ENV=$(echo "$PWD"/${VIRTUAL_ENV:5}/);;
    esac
    # Either find the venv or fail the subshell.
    . "$VIRTUAL_ENV/bin/activate"
  fi
  exec tmux \
    wait -L session\; \
    new -ADs "$PWD"\; \
      "${@:2}"
)

# Venv + Tmux wrappers.
alias vh='VIRTUAL_ENV="glob:*.venv" th'
alias vg='VIRTUAL_ENV="glob:*.venv" tg'
alias vd='VIRTUAL_ENV="glob:*.venv" td'

# Git aliases.
alias diff="git diff --no-index"
# Higher-speed keystrokes.
alias q="git status"
alias qa="git add --patch"
alias qaa="git add --all"
alias qd!="git reset --mixed"
alias qd="git reset --patch"
alias qdd!="git reset --hard"
alias qdd="git checkout --patch"
alias qq="git status --short"
alias qs="git show"
alias qsq="git show --stat"
alias qss="git log --patch"
alias qsso="git log --graph --oneline"
alias qssq="git log --stat"
alias qw="git diff"
alias qwq="git diff --stat"
alias qww="git diff --cached"
alias qwwq="git diff --cached --stat"
# Lower-speed keystrokes.
alias qc="git commit"
alias qca="git commit --amend"
alias qcam="git commit --amend --message"
alias qcan="git commit --amend --no-edit"
alias qcc="git commit --all"
alias qcca="git commit --all --amend"
alias qccam="git commit --all --amend --message"
alias qccan="git commit --all --amend --no-edit"
alias qccm="git commit --all --message"
alias qcm="git commit --message"
alias qp!="git push --force"
alias qp="git push"

incognito () { cognito off; }
cognito () {
  case ${1:-on} in
    (on)  [[ -z $HISTFILE ]] && HISTFILE="$HISTFILE__" && unset HISTFILE__;;
    (off) [[ -z $HISTFILE__ ]] && HISTFILE__="$HISTFILE" && unset HISTFILE;;
  esac
}
