#!/bin/bash


# I'm human, thanks
if [[ $(date +%Z) == 'UTC' ]]; then
    export TZ='America/Chicago'
fi

# because en_US.utf8 sorting is... dumb
export LC_COLLATE=C

export TERM="${TERM:-dumb}"
export EDITOR='vim'
export PROMPT_DIRTRIM=3

export VIRTUAL_ENV_DISABLE_PROMPT=true

# Embed an identity I control in all commits authored by me.
case ${GIT_COMMITTER_NAME:=$(git config --global user.name)} in
  ('') unset GIT_COMMITTER_NAME;;
  (*) export GIT_COMMITTER_NAME;;
esac
case ${GIT_COMMITTER_EMAIL:=$(git config --global user.email)} in
  ('') unset GIT_COMMITTER_EMAIL;;
  (*) export GIT_COMMITTER_EMAIL;;
esac

[[ ${TERM} == dumb ]] &&
    return 0

# Better shell scripting experience:
#   - Word split on newline ONLY.
#   - Disable pathname expansion for unquoted words.
#   - Patterns may expand to zero words.
#   - Patterns may use extended matching @(...) operators.
# With respect to completion routines, `extglob` is already enabled. Sadly, all
# the others interfere with widespread shell conventions and scripts.
#IFS=$'\n'
#set -f
#shopt -s nullglob
shopt -s extglob

: ${DEVELOPER_DIR:=$(xcode-select --print-path 2> /dev/null)}
for x in \
  /usr{,/local}/share/bash-completion/bash_completion \
  {,/usr/local}/etc/bash_completion \
  ${ELLIPSIS}data/profile/bash/completion.d/* \
  {,$DEVELOPER_DIR}/usr/share/git{,-core}/git-{prompt.sh,completion.bash} \
;
do
    [[ -r ${x} ]] &&
        . ${x}
done
# Rename _expand to _orig_expand.
eval _orig"$(declare -f _expand)"
# Never expand ~ during TAB completion.
_expand () { [[ "$cur" == \~*/* ]] || _orig_expand; }

# PS1 special sequences
#  0   reset/default
#  1   bold
#  5   blink
#  30  fg black
#  31  fg red
#  32  fg green
#  33  fg brown
#  34  fg blue
#  35  fg purple
#  36  fg cyan
#  37  fg gray
#  40  bg black
#  41  bg red
#  42  bg green
#  43  bg brown
#  44  bg blue
#  45  bg purple
#  46  bg cyan
#  47  bg gray
#  \u  username
#  \h  hostname
#  \$  terminal
#  \W  pwd /
#  \w  pwd ~

_esc () {
    printf '\['
    while ((${#*})); do tput ${c} ${1}; shift; done
    printf '\]'
}

_ps1 () { (

    e () { c= _esc "${@}"; }
    x () { c= _esc sgr0; c= _esc op; }
    f () { c=setaf _esc "${@}"; }
    b () { c=setab _esc "${@}"; }

    local u="$(x;f 3)\h"
    local w="$(x)"
    local v="${w}\${VIRTUAL_ENV:+\"$(x;f 5)\${VIRTUAL_ENV//@(*\/|.venv)} ${w}\"}"

    if [[ ${EUID} == 0 ]]; then
        local m="$(x;f 1)▶"
    else
        local m="$(x)▶"
    fi

    local s=( )

    [[ ${HOSTNAME} =~ ^ca- ]] &&
        s+=("$(f 2)★") ||
        s+=("$(f 1)⚑")

    [[ ${SSH_CONNECTION} =~ [0-9.]+ ]] &&
        s+=("$(f 4)⇅")

    ((${#s})) &&
        s=" ${s[*]} "

    local q='2>/dev/null'

    echo -e "\
${w}  ⎞ ${w}\D{%l:%M%P} ${v}$(x)${u}${s}
${w}  ⎥  \$(__git_ps1 '$(x;f 3)%s ' ${q})${w}\w
${w}  ⎥${m} $(x)"

) }

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize

# Enable history appending instead of overwriting.
shopt -s histappend

# Collapse multiple lines to one.
shopt -s cmdhist

# Change the window title of X terminals
case ${TERM} in
  [ixatE]term*|rxvt*|gnome*|interix)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\007"'
    ;;
  tmux|screen)
    PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/$HOME/~}\033\\"'
    ;;
esac

# flush HISTFILE constantly
PROMPT_COMMAND+='
history -a
'

# auto-update SSH_AUTH_SOCK within running shells
PROMPT_COMMAND+='
if [[ -n ${TMUX} && -n ${SSH_AUTH_SOCK} ]]; then
    unset SSH_AUTH_SOCK
    export $(tmux show-environment | grep ^SSH_AUTH_SOCK)
fi
'

use_color=false

# Set colorful PS1 only on colorful terminals.
# dircolors --print-database uses its own built-in database
# instead of using /etc/DIR_COLORS.  Try to use the external file
# first to take advantage of user additions.  Use internal bash
# globbing instead of external grep binary.
safe_term=${TERM//[^[:alnum:]]/?}   # sanitize TERM
match_lhs=""
[[ -f ~/.dir_colors   ]] && match_lhs="${match_lhs}$(<~/.dir_colors)"
[[ -f /etc/DIR_COLORS ]] && match_lhs="${match_lhs}$(</etc/DIR_COLORS)"
[[ -z ${match_lhs}    ]] \
  && type -P dircolors >/dev/null \
  && match_lhs=$(dircolors --print-database)
[[ $'\n'${match_lhs} == *$'\n'"TERM "${safe_term}* ]] && use_color=true

if ${use_color} ; then
  # Enable colors for ls, etc.  Prefer ~/.dir_colors #64489
  if type -P dircolors >/dev/null ; then
    if [[ -f ~/.dir_colors ]] ; then
      eval $(dircolors -b ~/.dir_colors)
    elif [[ -f /etc/DIR_COLORS ]] ; then
      eval $(dircolors -b /etc/DIR_COLORS)
    fi
  fi
    PS1=$(_ps1)
    ls --color=auto >/dev/null 2>&1 && _gnu_ls=true || _gnu_ls=false
    if ${_gnu_ls}; then
      alias ls='ls -F --color=auto'
    else
      alias ls='ls -F -G'
    fi
else
  if [[ ${EUID} == 0 ]] ; then
    # show root@ when we don't have colors
    PS1='\u@\h \W \$ '
  else
    PS1='\u@\h \w \$ '
  fi
fi


HISTCONTROL=ignoreboth:erasedups
HISTFILE=${ELLIPSIS}var/cache/bash/history
HISTFILESIZE=10000000
HISTIGNORE='[bf]g:[bf]g :exit:exit :cognito:cognito :incognito:incognito '
HISTSIZE=10000000
HISTTIMEFORMAT='%a %b %-d %-I:%M:%S %p  # '


[[ -r ${ELLIPSIS}data/profile/bash/aliases ]] &&
    . ${ELLIPSIS}data/profile/bash/aliases
