#!/bin/bash

[[ -f ~/.../self/data/profile/sh/interactive ]] &&
    . ~/.../self/data/profile/sh/interactive
[[ -f ~/.../self/data/profile/bash/interactive ]] &&
    . ~/.../self/data/profile/bash/interactive
