#!/bin/zsh

if env | grep -q '^CODEX'; then
    # Hack to pull in aliases
    set -i
fi

[[ -f ~/.../self/data/profile/sh/interactive ]] &&
  . ~/.../self/data/profile/sh/interactive
[[ -f ~/.../self/data/profile/zsh/interactive ]] &&
  . ~/.../self/data/profile/zsh/interactive
