#!/bin/bash

l () { ls -l "${@}"; }
s () { ssh -C "${@}"; }

la () { ls -la "${@}"; }
w3rk () { ssh -C -carcfour -p22065 w3rk; }

s.hypervisor () { _ssh_mdns root ${FUNCNAME}; }
#s.gateway () { _ssh_mdns anthony ${FUNCNAME}; }
s.gateway () { ssh -C -carcfour anthony@10.10.10.1; }
s.repository () { _ssh_mdns agent ${FUNCNAME}; }
s.s101 () { _ssh_mdns emily ${FUNCNAME}; }
s.git () { _ssh_mdns git ${FUNCNAME}; }
f.git () { _ssh_fs git ${FUNCNAME}; }

3knock () { for x in 2178 5621 5620; do ncat -w1 207.67.118.240 $x; sleep 0.5; done; }

complete -F _ssh s
